### ISSUE TITLE
Broadcasting/RR is not working in WoW - Retail on the newest Windows 11 build (24h2)

### ISSUE THREAD

**Issue by asmodeuska** [OpenMultiBoxing/OpenMultiBoxing#25] opened 2024-10-09 12:28 UTC
**Describe the bug**
The Round Robbin feature is not working on the newest Windows 11 update (24h2). The software can capture the new and existing wow windows, but can't interact with them. If I roll back to the previous windows 11 build the software works fine.

**To Reproduce**
0. Have Windows 11 - 24h2 build
1. Start WOB
2. Start multiple Wow windows
3. Press RR hotkey (mouse or keyboard, doesn't matter)
4. Nothing happens..

**Expected behavior**
The RR feature should broadcast every interaction what I'm making on the focus window to the other game windows.

**Game:**
WOW

**Settings:**
[OpenMultiBoxingSettingsqwe.txt](https://github.com/user-attachments/files/17308078/OpenMultiBoxingSettingsqwe.txt)

**Comment by WayneSheppard** [comment] 2024-10-19 13:03
Confirming the issue.  Key broadcasting is not working for me at all with 24h2.  Overlay works, window position works.  But not key broadcasting.

**Comment by mooreatv** [comment] 2024-10-24 18:17
Can you run with `-debug` and tell me what that debug window shows when you press keys during broadcasting?

**Comment by WayneSheppard** [comment] 2024-10-24 18:54
The debug window does nothing when I press keys that should be broadcast.  Below is the entire console output.  

Version 10.0.26100.2033
Windows 11, version 24H2, servicing stack update (KB5046306)
^this is the patch where it stopped working.



DEBUG OMB v8.1.2 called with -debug
DEBUG Original app_dir: C:/games/MB/OMB/OpenMultiBoxing-v8.1.2.exe/app (script C:/games/MB/OMB/OpenMultiBoxing-v8.1.2.exe/app/OpenMultiBoxing.tcl)
DEBUG Post exe detection app_dir: C:/games/MB/OMB
DEBUG Base settings: C:/games/MB/OMB/OpenMultiBoxingSettings.tcl
DEBUG In EXE, checking for code outside: C:/games/MB/OMB/OpenMultiBoxing.tcl
DEBUG geometry for mainWindowGeometry is at 1434,157
DEBUG displayInfo = {-extent {3840 0 5120 720} -workarea {3840 0 5120 720} -primary 0 -name {\\.\DISPLAY1}} {-extent {1920 0 3840 1080} -workarea {1920 0 3840 1080} -primary 0 -name {\\.\DISPLAY2}} {-extent {0 0 1920 1080} -workarea {0 0 1920 1032} -primary 1 -name {\\.\DISPLAY3}}
DEBUG Monitor 1 Extent   3840,0  - 5120,720
DEBUG Monitor 2 Extent   1920,0  - 3840,1080
DEBUG Monitor 3 Extent   0,0  - 1920,1080
DEBUG Unregistering previous hotkeys
DEBUG RegisterHotkey Ctrl-Shift-C Capture hk,capture CaptureOrUpdate
DEBUG RegisterHotkey Ctrl-Shift-Alt-M Start/Stop mouse tracking hk,mouseTrack MouseTracking
DEBUG RegisterHotkey Ctrl-Shift-N Focus next window hk,focusNextWindow FocusNextWindow
DEBUG RegisterHotkey Ctrl-Shift-P Focus previous window hk,focusPreviousWindow FocusPreviousWindow
DEBUG RegisterHotkey Ctrl-0xC0 Swap next window hk,swapNextWindow SwapNextWindow
DEBUG RegisterHotkey Ctrl-Shift-0xC0 Swap previous window hk,swapPreviousWindow SwapPreviousWindow
DEBUG RegisterHotkey Ctrl-Shift-F Focus follow mouse toggle hk,focusFollowMouse FocusFollowMouseToggle
DEBUG RegisterHotkey Ctrl-Shift-T Always on top toggle hk,stayOnTopToggle StayOnTopToggle
DEBUG RegisterHotkey Ctrl-Shift-O Overlay toggle hk,overlayToggle OverlayToggle
DEBUG RegisterHotkey Ctrl-Shift-R RoundRobin toggle hk,rrToggle RRToggle
DEBUG RegisterHotkey Ctrl-Shift-W Focus main window hk,focusMain FocusMain
DEBUG RegisterHotkey Ctrl-Shift-Alt-R Reset all windows to saved positions hk,resetAll ResetAll
DEBUG RegisterHotkey Ctrl-Shift-M Start/Stop mouse broadcasting hk,mouseBroadcast MouseBroadcast
DEBUG Settings (re)Loaded.
DEBUG In exe omb logo loaded
DEBUG nextWindow is 1 - args 
DEBUG SaveSettings base C:/games/MB/OMB/OpenMultiBoxingSettings.tcl (from cb )
OpenMultiBoxing v9.0.0 started...
DEBUG Control passed to local file C:/games/MB/OMB/OpenMultiBoxing.tcl
DEBUG .o3 -> 0xbf0c00 HWND -> 65548 HWND
DEBUG .__tooltip__ -> 0x21212 HWND -> 65548 HWND
DEBUG .o4 -> 0xba042e HWND -> 65548 HWND
DEBUG . -> 0x280d1c HWND -> 65548 HWND
DEBUG Found . to pause
DEBUG .o5 -> 0xbb0bbe HWND -> 65548 HWND
DEBUG .o1 -> 0x661116 HWND -> 65548 HWND
DEBUG .o2 -> 0x8508a6 HWND -> 65548 HWND
DEBUG Done refreshing window ids - retry #2 0
DEBUG found OMB 1! : {1376468 HWND} : 1376468 HWND
DEBUG NEWX Focus for 1 is 1376468 HWND, tid 9276
DEBUG Setting focus hotkey for 1 / OMB 1: Ctrl-F1
DEBUG RegisterHotkey Ctrl-F1 Focus window 1 hk1,focus FocusN 1 true
DEBUG Setting swap hotkey for 1 / OMB 1: Ctrl-Shift-F1
DEBUG RegisterHotkey Ctrl-Shift-F1 Swap window 1 hk1,swap SetAsMain 1
DEBUG n is 1 nextWindow is 1 maxNumW is 1
DEBUG nextWindow is 2 - args nextWindow {} write
DEBUG Update for 1 in pos 1 : 0,0 1920x1032 - 0
DEBUG Clearing stay on top for 1376468 HWND
DEBUG found OMB 2! : {593922 HWND} : 593922 HWND
DEBUG NEWX Focus for 2 is 0 HWND, tid 24840
DEBUG Setting focus hotkey for 2 / OMB 2: Ctrl-F2
DEBUG RegisterHotkey Ctrl-F2 Focus window 2 hk2,focus FocusN 2 true
DEBUG Setting swap hotkey for 2 / OMB 2: Ctrl-Shift-F2
DEBUG RegisterHotkey Ctrl-Shift-F2 Swap window 2 hk2,swap SetAsMain 2
DEBUG n is 2 nextWindow is 2 maxNumW is 2
DEBUG nextWindow is 3 - args nextWindow {} write
DEBUG Update for 2 in pos 2 : 1920,0 960x540 - 0
DEBUG Clearing stay on top for 593922 HWND
DEBUG OMB 3 not found, skipping
DEBUG OMB 4 not found, skipping
DEBUG OMB 5 not found, skipping
DEBUG OMB 6 not found, skipping
DEBUG nextWindow is 3 - args nextWindow {} write
DEBUG Hotkey ok=1 for RoundRobin toggle - RRToggle
DEBUG RRupdate 1
DEBUG RRkey W -> 0x57
DEBUG RRkey A -> 0x41
DEBUG RRkey S -> 0x53
DEBUG RRkey D -> 0x44
DEBUG ResetIgnoredKeys 0 17 1 18 2 3 4 5 6 7 83 65 68 16 87
DEBUG Reset all Broadcasting key states
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG Hotkey ok=1 for RoundRobin toggle - RRToggle
DEBUG RRupdate 0
DEBUG Reset all Broadcasting key states
DEBUG Hotkey ok=1 for RoundRobin toggle - RRToggle
DEBUG RRupdate 1
DEBUG RRkey W -> 0x57
DEBUG RRkey A -> 0x41
DEBUG RRkey S -> 0x53
DEBUG RRkey D -> 0x44
DEBUG ResetIgnoredKeys 0 17 1 18 2 3 4 5 6 7 83 65 68 16 87
DEBUG Reset all Broadcasting key states
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window
DEBUG FocusIn: no foreground window

**Comment by mooreatv** [comment] 2024-10-24 20:38
hmm so you press say the space bar with broadcasting on and nothing? so it looks like it's not even seeing the key events anymore, maybe some sort of privacy or accessibility settings?

also to clarify you are talking about broadcasting and not round robin (even if in the log it may say RR but in 8.1.2 (or 9.0.0) it's about broadcasting)

**Comment by mooreatv** [comment] 2024-10-24 20:39
hmmm that "no foreground window" is fishy too

**Comment by WayneSheppard** [comment] 2024-10-24 21:49
Sorry, the issue for me is broadcasting.  I've never tried RR.

I get "no foreground window" each time I click into one of my gaming windows.    Pressing keys works in my active window, but nothing in the other windows or in the logs.  I get the overlay arrow, it turns on and off when I press ctrl-shift-R, and appropriate log messages.

And I am running 9.0.0
DEBUG OMB message -type ok -icon info -title {Already uptodate} -message {You're already running the latest version v9.0.0}

**Comment by werkn** [comment] 2024-10-25 23:32
I can confirm the exact same behaviour

**Comment by werkn** [comment] 2024-10-27 22:44
Only caveat to add with myself is I'm running 24H2 in Windows ARM under Parallel's but I still have functioning WoW Multiboxing binary with RR working so likely not related.

**Comment by Dunkleseele123** [comment] 2024-10-29 06:42
I can confirm the same issue, neither mouse nor keyboard broadcasting worked after the windows 24H2 update. I rolled back now it works again. I dont want to wait out on the update from windows too long, is there any fix yet? Thanks in advance!

**Comment by Dunkleseele123** [comment] 2024-11-09 19:31
Any update so far?

**Comment by Therieth** [comment] 2024-11-21 19:38
Same issue, still haven't found a way to fix it

**Comment by Therieth** [comment] 2024-11-22 04:54
Deprecated API starting 24h2?
https://learn.microsoft.com/en-us/windows/win32/winmsg/journalplaybackproc

Its hit other softwares too like AHK and some others like iNEWS workstation, they have fixed it by just using a different API

**Comment by mooreatv** [comment] 2024-12-21 17:51
Thanks a lot for this @rostrage and my apologies I don't get github updates - I just got finally offered that 24H2 update on my pc so I am upgrading and will confirm and release the fix

**Comment by mooreatv** [comment] 2024-12-21 19:55
fixed in https://github.com/OpenMultiBoxing/OpenMultiBoxing/releases/tag/v9.0.1 please confirm

**Closed by mooreatv** 2024-12-21 19:55 UTC
Labels: bug
